spring.application.name=HomeTaskManager
server.port=9090

spring.datasource.url=jdbc:h2:mem:bdh2
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
localhost:9090/h2-console
spring.h2.console.path=/h2-ui